Release 1.2.0
EMERALD0874/AudioLoader-PackDB pull request #56
Opened 2022-10-11 00:59 UTC by beebls

This adds new documentation for the mappings feature, and adjusts the workflows to push to the new release 1.2.0

2022-10-11 19:09 UTC, EMERALD0874 requested changes
Did you test the Python script to make sure repo validation still works? I think the new mappings feature may not be super cooperative.

2022-10-11 19:09 UTC, EMERALD0874 commented on README.md
>    "manifest_version": 1,
```suggestion
  "manifest_version": 2,
```
Manifest version should be the latest.

2022-10-11 22:47 UTC, beebls commented
I am going to attempt to work on new CI validation for the mappings feature.
Do not merge yet

2022-10-11 23:30 UTC, beebls commented
CI has been modified, after merging we will need to check to ensure that it works and builds correctly

2022-10-11 23:33 UTC, beebls commented
I bumped the github release the CI uses to clone the megajson, and this appears to be making the CI error out, we may have to manually clone the old themes.json before it begins to work.

2022-10-13 01:21 UTC, EMERALD0874 approved these changes
Ignoring the
# ***HEINOUS TYPOES IN YOUR REPOSITORY***
yeah we good

2022-10-13 01:22 UTC, merged

2022-10-13 01:22 UTC, suchmememanyskill commented
Rekt